/**
 * Agent Layer — Type definitions for Quill agent.
 */

import type { FigmaTextNode } from "../mcp/mcp.types.js";

export type CopyFormat =
  | "confirmation_success"
  | "confirmation_prompt"
  | "destructive"
  | "notification";

/** Variant of copy generated by the agent */
export interface CopyVariant {
  headline: string;
  body?: string;
  ctas: string[];
}

export interface SectionReasoning {
  headline?: string;
  body?: string;
}

/** Full structured response from the Quill agent */
export interface AgentResponse {
  format: CopyFormat;
  formatNote?: string;
  needsClarification?: boolean;
  clarifyingQuestions?: string[];
  approved?: boolean;
  approvalNote?: string;
  original?: string;
  recommended: number;
  variants: CopyVariant[];
  reasoning: SectionReasoning;
}

/** Input to the Quill agent */
export interface GenerateCopyInput {
  prompt: string;
  figmaFileId?: string;
  figmaNodes?: FigmaTextNode[];
  provider?: string;
  apiKey?: string;
  figmaToken?: string;
  localUrl?: string;
  localModel?: string;
  localApiKey?: string;
  options?: {
    variantCount?: number;
    includeReasoning?: boolean;
  };
}
