/**
 * Agent Layer — Type definitions for Quill agent.
 */

import type { FigmaTextNode } from "../mcp/mcp.types.js";

/** Variant of copy generated by the agent */
export interface CopyVariant {
  headline: string;
  cta: string;
  labels: string[];
}

/** A grammar fix suggestion */
export interface GrammarFix {
  original: string;
  corrected: string;
  rule: string;
}

/** Full structured response from the Quill agent */
export interface AgentResponse {
  variants: CopyVariant[];
  fixes: GrammarFix[];
  reasoning: string[];
}

/** Input to the Quill agent */
export interface GenerateCopyInput {
  prompt: string;
  figmaFileId?: string;
  figmaNodes?: FigmaTextNode[];
  provider?: string;
  apiKey?: string;
  figmaToken?: string;
  localUrl?: string;
  localModel?: string;
  localApiKey?: string;
  options?: {
    variantCount?: number;
    fixGrammar?: boolean;
    includeReasoning?: boolean;
  };
}
